export const HOME = 'HOME';
export const ENTRY = 'ADD LOG';
export const LOGIN = 'LOG IN';
export const SIGNUP = 'SIGN UP';
export const PROFILE = 'PROFILE';
export const ABOUT = 'ABOUT';

export const MEAL = 'MEAL';
export const ALL = 'ALL FOOD';
export const FAVORITES = 'FAVORITES';
export const VEGETABLE = 'VEGETABLE';
export const FRUIT = 'FRUIT';
export const MEAT = 'MEAT | FISH';
export const MILK = 'MILK';
export const RICE = 'RICE';
export const FATS = 'FATS';
export const SUGAR = 'SUGAR';
export const FREE = 'FREE FOODS';
export const BEVERAGE = 'BEVERAGE';
